### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by zack-emmert** [GnaspGames/Smelt#40]
When I attempt to compile the demo file, I receive the error: `/usr/bin/env: ‘node\r’: No such file or directory`

**Comment by GnaspGames** [comment]
Thanks, I'll check it out.

**Comment by GnaspGames** [comment]
May I ask, What OS are you running this on?

**Comment by zack-emmert** [comment]
I'm using a fully updated build of Debian Sid.

**Comment by GnaspGames** [comment]
Thanks. I've not tested this recently on Linux. I suspect from the error that I've written a path incorrectly. 

I'll run it myself on Linux and see what I find.

**Comment by GnaspGames** [comment]
It looks like this was a repeat of issue #16 - it should be fixed now if you upgrade

`npm install smelt-cli -g`

**Comment by zack-emmert** [comment]
Just updated to the new version, this is the new error: `/usr/bin/env: ‘node’: No such file or directory
`

**Comment by zack-emmert** [comment]
Ignore my previous comment, my node executable was named nodejs, not node, symlinking one to the other fixed the issue

**Comment by GnaspGames** [comment]
Glad it's sorted. Thanks for the report!
