### ISSUE TITLE
Lines containing a URL ignored due to //

### ISSUE THREAD

**Issue by Moesh-zz** [GnaspGames/Smelt#45]
Comments should be differentiated from URLs, but also tracked if used in JSON or NBT data.

**Comment by GnaspGames** [comment]
Okay, so this is a fiddly one. 

The issue is `//` found withing a string. 
A string is anything found withing double quotes. Example:

```
"value": { "translate": "Ideal Development Environment\nby Moesh (http://moesh.ca)"}
```

My solution is going to be to match strings that contain `//` and ignore them, while still removing other comments.
