### ISSUE TITLE
'Aliases' rather than commands

### ISSUE THREAD

**Issue by ckwakman** [GnaspGames/Smelt#52]
Not sure if I'm using proper terminology, but anyway…

Rather than having
`/scoreboard players tag <entity> <add/remove> <tag> <NBT data>`
Smelt could have
`<entity> + <tag> <NBT data>`

Likewise:
`/execute <entity> ~ ~ ~ /execute <entity> ~ ~ ~` to `/<entity> <entity>`
`/scoreboard players operation <entity 1> <objective> <operation> <entity 2> <objective>` to `<entity 1> <objective> <operation> <entity 2> <objective>`

It'd make code easier (and nicer) to read, and less prone to being 'read' wrong by Smelt and minecraft (e.g. forgetting to add a space between <entity> and the next tilda)

**Comment by JBartelsson** [comment]
You could create a custom FileParser.js for yourself and publish it. Basically you create a extension pack so Gnasp can assess it.

**Comment by GnaspGames** [comment]
I would recommend looking into how the plugins system works; it would not be hard to implement:

`!tag <entity> + <tag> <NBT data>`

All sorts of commands could be shortened using bang commands.

**Comment by GnaspGames** [comment]
I'm closing this because the solution is plugins/bang commands. If you want to open a request for specific built in bang commands, please do!
