### ISSUE TITLE
Conditional Corners fix breaks with "executeAs"

### ISSUE THREAD

**Issue by destruc7i0n** [GnaspGames/Smelt#59]
If you were to have command blocks that are conditional at the edge of the command block line, Smelt will automatically add a testforblock to account for the edge.

If there is `>{"executeAs": ""}` before the edge, the testforblock will be executed by the player specified in the `executeAs`.

**Comment by GnaspGames** [comment]
@destruc7i0n This should be okay now in v1.0.1 :smile:
