### ISSUE TITLE
Plugins not working after /execute

### ISSUE THREAD

**Issue by ckwakman** [GnaspGames/Smelt#60]
E.g.
`/execute <entity> ~ ~ ~ !math <objective>.<entity> <operation> <expression>`
Does not work, even if it logically should.
Doing the below _will_ work:
`> {"executeAs":"<entity>"}`
`!math <objective>.<entity> <operation> <expression>`

**Comment by GnaspGames** [comment]
Yeah Smelt doesn't currently support using a bang command _inside_ another command. 

You should use the "executeAs" JSON property instead.

**Comment by ckwakman** [comment]
Ah, okay! Just thought it was a bit of an inconsistency.

2016-08-29 23:00 GMT+08:00 Gnasp notifications@github.com:
