### ISSUE TITLE
Error setting the MinecraftVersion target on the config.

### ISSUE THREAD

**Issue by VexSpectre** [GnaspGames/Smelt#63]
![image](https://cloud.githubusercontent.com/assets/20722837/18080847/61cb1f4a-6e54-11e6-8028-83ecb65ff878.png)
_Image by @t70 on Discord_

The console returns all the parameters as an invalid value when we try to set it up from the configuration option added with #53

**Comment by GnaspGames** [comment]
Thanks for the report! 

Fixed in 1.1.0-pre4 :zap:
