### ISSUE TITLE
Output of commands before compilation

### ISSUE THREAD

**Issue by destruc7i0n** [GnaspGames/Smelt#64]
It would be useful from a debugging standpoint to allow for the commands to put outputted before compilation into a one command.

**Comment by GnaspGames** [comment]
@destruc7i0n 

Not sure if you've seen this, but when you add the `--debug` switch you do get a lot of additional output.

`smelt compile MYFILE.mcc --debug`

Look out for the "CREATE COMMAND BLOCK" lines, they should show you the commands being created inside each cmd block. 

E.g.

```
* CREATE COMMAND BLOCK
  say 10
   -> setblock ~11 ~-1 ~4 chain_command_block 5 replace {Command:"/execute @e[tag=Smelt_SYSTEM] ~ ~ ~ say 10",auto:1b}
```

Would that be enough information, or are you thinking of something else?

**Comment by destruc7i0n** [comment]
I actually found this a while back, forgot to close this, I'll close it now.
