### ISSUE TITLE
Option in config to disable the automatic wraparound near the chunk boundary

### ISSUE THREAD

**Issue by ReverendQ** [GnaspGames/Smelt#69]
Very often, systems require knowledge of the current direction of the command blocks (for instance, lorgon111's inline repeaters, conditional inverters, etc). It would be useful to be able to just have a long, straight line to ensure that the direction is always correct in these cases.

I understand that this might cause issues with the automatic chunk-based clear area. I'm not sure how to address that, to be honest. Maybe it'd be vertical instead of horizontal, so it'd still be within the chunk?

**Comment by GnaspGames** [comment]
With the changes being added in issue #14 it will be possible for you to specify a different "module size". You could make it as large are you want. 

This is currently released in the 1.1.0 pre-release. Install with `npm install smelt-cli@pre -g`

**Comment by GnaspGames** [comment]
BTW, sorry for slow reply. September was a busy busy month, and not computer is started playing up. 😢 

So I'm still a little limited on what development work I can do.
