### ISSUE TITLE
When TrackOutput is set to enabled, don't add the TrackOutput tag

### ISSUE THREAD

**Issue by ReverendQ** [GnaspGames/Smelt#73]
The blocks are automatically set to TrackOutput 1 when spawned unless specified otherwise in the game. This means adding a bunch of "TrackOutput:1b" tags increases the character limit. There are some .mcc files of mine that no longer work on the prerelease as a result of this.

**Comment by GnaspGames** [comment]
Hey!

I know this was discussed in our Discord chat. I forgot to come back here to update it.

> "The blocks are automatically set to TrackOutput 0 when spawned unless specified otherwise in the game" 

I've been reliably told that TrackOutput is true by default. Even the gamerule used when creating blocks manual doesn't work for cmd blocks that are created via commands. 

So when it needs to be false, this means that the tag must be included. Sorry.

**Comment by ReverendQ** [comment]
For some reason, I said "enabled" instead of "disabled" and "0" instead of "1". Also, I'm pretty sure I'm the person who told you that. You should reopen the issue now that I've fixed that triple-typo.
