### ISSUE TITLE
For conditionals in corners, the two command blocks using {SuccessCount:1} should use {SuccessCount:0}

### ISSUE THREAD

**Issue by hanmindev** [GnaspGames/Smelt#74]
Right now, conditional corners use {SuccessCount:1} which doesnt work when the successcount is like 2, but {SuccessCount:0} fixes that.

**Comment by GnaspGames** [comment]
Hey. Yeah this has already been looked at. See #68. The fix is in pre-release at the moment. But unfortunately your way might break in the long run (again, see #68).

Thanks,
Phil
