### ISSUE TITLE
!loop adds a repeating command block with "searge" inside

### ISSUE THREAD

**Issue by quat1024** [GnaspGames/Smelt#75]
https://github.com/GnaspGames/Smelt/blob/master/BangCommands/Included/loop.js#L35

![](http://i.imgur.com/pXZeCIo.png)

But... why?

**Comment by GnaspGames** [comment]
It's used to make sure that there is a successfully run command block. The 'searge' cmd block doesn't do anything other than that. 

I see you've also asked this question in the Discord chat and had, so I'll close it here. Please continue to raise questions in Discord if you have more.
