### ISSUE TITLE
An option to have auto:on applied to impulse-chain or repeating-chain command blocks

### ISSUE THREAD

**Issue by Moesh-zz** [GnaspGames/Smelt#76]
For readabililty, I find myself typing out this quite often:

```
# ResetLevel
>{"type":"impulse-chain","auto":false}
/searge
>{"auto":true}
    /say hi
```

As I'm bug fixing, being able to glance through my code quickly by grouping lines of code together has been a great help. When I use the `>{}` tag, it's because I'm switching something to conditional, or doing some very particular logic. Having to apply `>{"auto":true}` and split up a line of my code (or adding `/searge`, as I have been) to each line has begun to bloat my code.

Would introducing a rule to turn `<repeating|impulse>-chain` command blocks on by default work?

**Comment by GnaspGames** [comment]
I've added this to the 1.1.0 pre-release (version 1.1.0-pre6)

You can install it using `npm install smelt-cli@pre -g` to test.

More details available here: http://smelt.gnasp.com/prereleases.html
