### ISSUE TITLE
startModuleZ has no effect on Z coordinate starting position

### ISSUE THREAD

**Issue by ckwakman** [GnaspGames/Smelt#82]
Increasing "moduleStartZ": 0 to "moduleStartZ": 1 will raise the module by one in the y-axis when expected behaviour would be movement on the z-axis

**Comment by GnaspGames** [comment]
Thanks for the bug report. 

I'll have a look into it.

**Comment by GnaspGames** [comment]
Yup, looks like a type here:

https://github.com/GnaspGames/Smelt/blob/20f4970cff694961353ebeedd60f7b0cb11a7688/Compiler/CommandCreator.js#L394

The parameters `startX, startZ, startY` are being passed through in the wrong order. 

I'll submit a fix and release a new pre-release. I'm not in a position to test the fix at the moment, would you be able to let me know if it works? 

If so, I think it's about time that I finish the pre-release cycle and release 1.1.0 properly. 

Thanks!

**Comment by GnaspGames** [comment]
`1.1.0-pre9` has now been released. Let me know how you get on?

**Comment by ckwakman** [comment]
Sure, I'll test it!

2017-01-17 22:24 GMT+08:00 Gnasp <notifications@github.com>:

**Comment by GnaspGames** [comment]
> bananenbroek4 - 01/21/2017
> I don't think moduleStartZ works still
> Y works now though

**Comment by GnaspGames** [comment]
@bananenbroek4 Sorry it's taken a while; but this should now be fixed in `1.1.0-pre10`.
