### ISSUE TITLE
Last comment doesn't count as a comment

### ISSUE THREAD

**Issue by hanmindev** [GnaspGames/Smelt#85]
If you put in smelt:
/say hi
/say hello
//say test
//say yo
//say greetings

It should display
[@] hi
[@] hello

but instead it displays
[@] hi
[@] hello
[@] greetings

**Comment by GnaspGames** [comment]
Looks like the regular expression to remove comments it igoring the end of line.

**Comment by GnaspGames** [comment]
This was fixed in version 1.1.1
