### ISSUE TITLE
Adding a JSON Property to handle TrackOutput from inside the .mcc

### ISSUE THREAD

**Issue by Plagiatus** [GnaspGames/Smelt#90]
It would be really nice if one could change the TrackOutput property from inside the -mcc file, using the JSON format.

Example:  
`>{"TrackOutput":true}`

This would allow for easier and quicker debugging.

**Comment by GnaspGames** [comment]
@Plagiatus So,.. I haven't tested this, but it appears that a "trackOutput" JSON property already exists. 

At least [it is in the code](https://github.com/GnaspGames/Smelt/blob/1-1-stable/Compiler/CommandCreator.js#L352). Can you test this? 

If it works, I'll add it to the documentation.

**Comment by GnaspGames** [comment]
It needs to be with a lowercase "t" on "trackOutput". That's consistent with the other properties.

**Comment by GnaspGames** [comment]
I'm closing this now we know it's already in there!
